#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproofer https://qmetry.github.io/qaf/index.html --log-level ":stdout" --file-ignore "/.+\/javadoc.+/" --alt-ignore="/.+\/images.+/","images.+/","images.+.svg" --allow-hash-href
bundle exec htmlproofer ./_site --log-level ":stdout" --file-ignore "/.+\/javadoc.+/" --alt-ignore="/.+\/images.+/","images.+/","images.+.svg" --allow-hash-href
